services:
  fpga-compiler:
    image: haiphanthanh10272005/fpga-compiler:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    # Usage: docker-compose run fpga-compiler fpga.bat build -Project lab2
