[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 57600
upload_port = COM6
upload_flags = --before default_reset --after hard_reset --no-compress --baud 57600
